# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes: 
      - "./data:/data/db"
    ports:
      - "27017:27017"
    

  mongo-express:
    image: mongo-express
    restart: always
    expose:
      - "8081"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on: 
      - "mongo"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    links:
      - mongo

